auctions/urls.py
from django.urls import path

from . import views

app_name = "commerce"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create_listing", views.create_listing, name="create_listing"),
    path("listing/<listingTitle>", views.listing, name="listing"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("categories", views.categories, name="categories"),
    path("category/<category>", views.category, name="category")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):
    pass


class CreateListing(forms.Form):
    title = forms.CharField(max_length=48, label="Title",
                            widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'}), max_length=210, label="Description")
    startingBid = forms.FloatField(
        label="Starting Bid", widget=forms.NumberInput(attrs={'class': 'form-control', 'step': "0.01"}))
    imageURL = forms.CharField(
        max_length=100, label="ImageURL (optional)", required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    category = forms.CharField(max_length=48, label="Category",
                               widget=forms.TextInput(attrs={'class': 'form-control'}))


class Listing(models.Model):
    title = models.CharField(max_length=48)
    description = models.CharField(max_length=210)
    startingBid = models.DecimalField(max_digits=10, decimal_places=2)
    imageURL = models.CharField(max_length=300)
    category = models.CharField(max_length=48)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="createdBy")
    status = models.CharField(max_length=6)

    def __str__(self):
        return f"title:{ self.title } imageURL:{ self.imageURL } description:{ self.description } startingBid:{ self.startingBid } category:{ self.category } createdBy: { self.user }"


class PlaceBid(forms.Form):
    bid = forms.FloatField(label="",
                           widget=forms.TextInput(attrs={'placeholder': 'Bid', 'class': 'form-control', 'name': 'bid', 'step': "0.01"}))


class Bid(models.Model):
    placedBy = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="placedBy")
    placedTo = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="placedTo")
    amount = models.DecimalField(
        max_digits=10, decimal_places=2)

    def __str__(self):
        return f"user:{ self.placedBy } bid:{ self.amount } on:{ self.placedTo }"


class Watchlist(models.Model):
    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="listingWatchlist")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="userWatchlist")

    def __str__(self):
        return f"listing:{self.listing} user:{self.user}"


class CommentForm(forms.Form):
    title = forms.CharField(max_length=48, label="Title",
                            widget=forms.TextInput(attrs={'class': 'form-control'}))
    comment = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'}), max_length=450, label="Comment")


class Comment(models.Model):
    title = models.CharField(max_length=48)
    comment = models.CharField(max_length=450)
    commentBy = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commentBy")

    def __str__(self):
        return f"User: { self.commentBy } title: { self.title } comment: { self.comment }"

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
import re

from .helper import getHighestBidder, getWatchlist, checkForBid

from .models import User, Listing, CreateListing, PlaceBid, Bid, Comment, Watchlist, CommentForm


def index(request):
    try:
        checkBid = Bid.objects.filter(
            placedTo=Listing.objects.get(title=title)).order_by('-id')[0]
        currentBid = re.findall("bid:(.+) on:", str(checkBid))[0]
    except:
        currentBid = 0

    if request.user.is_authenticated:
        watchlist, onwatchlist = getWatchlist(request.user, None)
    else:
        watchlist = ""

    lm = []
    ls = Listing.objects.all()
    for listing in ls:
        try:
            checkBid = Bid.objects.filter(
                placedTo=Listing.objects.get(title=listing.title)).order_by('-id')[0]
            currentBid = checkBid.amount
        except:
            currentBid = 0

        if float(listing.startingBid) <= float(currentBid):
            bid = currentBid
        else:
            bid = listing.startingBid

        la = {
            "title": listing.title,
            "description": listing.description,
            "bid": bid,
            "imageURL": listing.imageURL,
            "category": listing.category
        }
        lm.append(la)

    return render(request, "auctions/index.html", {
        "listings": lm,
        "watchlistLen": len(watchlist)
    })


def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("commerce:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("commerce:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("commerce:index"))
    else:
        return render(request, "auctions/register.html")


def categories(request):
    if request.method == "POST":
        category = Listing.objects.get(category=request.POST["category"])
        return render(request, "auctions/category.html", {
            "category": category
        })

    listings = Listing.objects.all()
    categories = []

    for listing in listings:
        categories.append(listing.category)

    if request.user.is_authenticated:
        watchlist, onwatchlist = getWatchlist(request.user, None)
    else:
        watchlist = ""

    return render(request, "auctions/categories.html", {
        "categories": categories,
        "watchlist": watchlist,
        "watchlistLen": len(watchlist)
    })


def category(request, category):
    if request.user.is_authenticated:
        watchlist, onwatchlist = getWatchlist(request.user, None)
    else:
        watchlist = ""

    lm = []
    ls = Listing.objects.all()

    for listing in ls:
        updatedListing = checkForBid([listing])
        lm.append(updatedListing)

    print(lm)
    return render(request, "auctions/category.html", {
        "listings": lm,
        "category": lm[0]["category"],
        "watchlistLen": len(watchlist)
    })


def create_listing(request):
    if request.method == "POST":
        imageURL = request.POST["imageURL"]
        if imageURL == "":
            imageURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRJQ9xu5I_En7x6FYaQ8Mlf2QSMCg1cFAUu7w&usqp=CAU"

        ls = Listing(title=request.POST["title"], description=request.POST["description"],
                     startingBid=str(format(float(request.POST["startingBid"]), '.2f')), imageURL=imageURL, category=request.POST["category"], user=request.user, status="opened")
        ls.save()

    if request.user.is_authenticated:
        watchlist, onwatchlist = getWatchlist(request.user, None)
    else:
        watchlist = ""

    return render(request, "auctions/create_listing.html", {
        "createListing": CreateListing,
        "watchlistLen": len(watchlist)
    })


def listing(request, listingTitle):
    if request.method == "POST":
        if request.user.is_authenticated:
            # Get type of action
            try:
                action = request.POST["action"]
            except:
                action = None

            if action == "close_auction":
                getListing = Listing.objects.get(
                    title=request.POST["listingTitle"])
                getListing.status = "closed"
                getListing.save()

            if action == "comment":
                comment = Comment(
                    title=request.POST["title"], comment=request.POST["comment"], commentBy=User.objects.get(username=request.POST["commentBy"]))
                comment.save()

            # if action is related to watchlist actions
            if action == "watchlist_add" or action == "watchlist_remove":
                if action == "watchlist_add":
                    watchlistUpdate = Watchlist(
                        user=User.objects.get(id=request.user.id), listing=Listing.objects.get(
                            title=request.POST["watchlistItem"]))
                    watchlistUpdate.save()

                if action == "watchlist_remove":
                    watchlistUpdate = Watchlist.objects.get(
                        user=request.user, listing=Listing.objects.get(title=request.POST["watchlistItem"]))
                    watchlistUpdate.delete()

            if action == "bid":
                currentBid = request.POST["currentBid"]
                bidPlaced = request.POST["bid"]
                getObject = Listing.objects.filter(
                    title=f'{ listingTitle }')

                # Look if there is was a bid so far
                updatedListing = checkForBid(getObject)

                # Check for watchlist
                if request.user.is_authenticated:
                    watchlist, onwatchlist = getWatchlist(
                        request.user, getObject)

                if float(bidPlaced) >= float(currentBid):
                    status = "success"
                    message = "Your bid was successfully set!"
                    updateBid = Bid(placedBy=User.objects.get(id=request.user.id), placedTo=Listing.objects.get(
                        title=request.POST["placedTo"]), amount=bidPlaced)
                    updateBid.save()

                else:
                    status = "error"
                    message = "Your bid must be higher than the current price!"

                return render(request, "auctions/listing.html", {
                    "listing": updatedListing,
                    "placeBid": PlaceBid,
                    "watchlist": onwatchlist,
                    "watchlistLen": len(watchlist),
                    "status": status,
                    "message": message
                })

    getObject = Listing.objects.filter(title=f'{ listingTitle }')
    message = ""

    # Check for watchlist
    if request.user.is_authenticated:
        watchlist, onwatchlist = getWatchlist(request.user, getObject)
    else:
        onwatchlist = 0
        watchlist = ""

    # Look if there is was a bid so far
    updatedListing = checkForBid(getObject)

    # Get highestBidder if status == closed
    highestBidder = None
    if updatedListing["status"] == "closed":
        highestBidder = getHighestBidder(updatedListing)

    # Comments
    try:
        comments = Comment.objects.all()
    except:
        comments = None

    return render(request, "auctions/listing.html", {
        "listing": updatedListing,
        "placeBid": PlaceBid,
        "watchlist": onwatchlist,
        "watchlistLen": len(watchlist),
        "message": message,
        "commentForm": CommentForm,
        "comments": comments,
        "highestBidder": highestBidder
    })


def watchlist(request):
    if request.user.is_authenticated:
        # Check for watchlist
        watchlist, onwatchlist = getWatchlist(request.user, None)

        # Listing watchlist items
        current_user = request.user
        getWatchlistItems = Watchlist.objects.filter(
            user=f'{ current_user.id }')
        watchlistItems = []
        for entry in getWatchlistItems:
            try:
                currentBid = Bid.objects.filter(placedTo=Listing.objects.get(
                    title=entry.listing.title)).order_by('-id')[0].amount
            except:
                currentBid = 0

            if entry.listing.startingBid <= currentBid:
                bid = currentBid
            else:
                bid = entry.listing.startingBid
            watchlistItems.append(
                {
                    "title": entry.listing.title,

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Categories:</h2>
<div>
    {% for category in categories %}
    <form action="{% url 'commerce:category' category %}" method="post">
        {% csrf_token %}
        <input class="catButton" type="submit" value="{{ category }}" name="category">
    </form>
    {% endfor %}
</div>
<div class="wrapper">
</div>
{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Category: {{ category }}</h2>
{% for listing in listings %}
<div id="listing">
    <div id="imgOuter">
        <div style="width:100%;">
            <img src="{{ listing|get_item:"imageURL" }}">
        </div>
    </div>
    <div id="descriptionOuter">
        <div>
            <h4><a href="{% url 'commerce:listing' listing.title %}">{{ listing.title }}</a></h4>
        </div>
        <div><b>Price:</b> ${{ listing|get_item:"bid" }}</div>
        <div>{{ listing|get_item:"description" }}</div>
    </div>
</div>
{% endfor %}
{% endblock %}

auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Active Listings</h2>
<div class="wrapper">
    <form action="{% url 'commerce:create_listing' %}" method="post">
        <div class="form-group">
            {% csrf_token %}
            {{ createListing }}
            <input id="submit" class="btn btn-primary" type="submit" value="Create Listing" name="newListing">
        </div>
    </form>
</div>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Active Listings</h2>
{% for listing in listings %}
<div id="listing">
    <div id="imgOuter">
        <div style="width:100%;">
            <img src="{{ listing|get_item:"imageURL" }}">
        </div>
    </div>
    <div id="descriptionOuter">
        <div>
            <h4><a href="{% url 'commerce:listing' listing.title %}">{{ listing.title }}</a></h4>
        </div>
        <div><b>Price:</b> ${{ listing|get_item:"bid" }}</div>
        <div>{{ listing|get_item:"description" }}</div>
    </div>
</div>
{% endfor %}
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Auctions{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
</head>

<body>
    <h1>Auctions</h1>
    <div>
        {% if user.is_authenticated %}
        Signed in as <strong>{{ user.username }}</strong>.
        {% else %}
        Not signed in.
        {% endif %}
    </div>
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'commerce:index' %}">Active Listings</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'commerce:categories' %}">Categories</a>
        </li>
        <li style="display:flex; flex-direction: row; align-items: center;" class="nav-item">
            <a class="nav-link" href="{% url 'commerce:watchlist' %}">Watchlist</a>
            {% if watchlistLen > 0 %}
            <span id="watchlistNum">{{ watchlistLen }}</span>
            {% endif %}
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'commerce:create_listing' %}">Create Listing</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'commerce:logout' %}">Log Out</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'commerce:login' %}">Log In</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'commerce:register' %}">Register</a>
        </li>
        {% endif %}
    </ul>
    <hr>
    {% block body %}
    {% endblock %}
</body>

</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Listing: {{ listing|get_item:"title" }}</h2>
{% if user.is_authenticated %}
{% if status == "error" %}
<div class="alert alert-danger" role="alert">
    <span>{{ message }}</span>
</div>
{% endif %}
{% if status == "success" %}
<div class="alert alert-success" role="alert">
    <span>{{ message }}</span>
</div>
{% endif %}
{% if listing|get_item:"status" == "closed" %}
{% if request.user.id == highestBidder.id %}
<div class="alert alert-success" role="alert">
    <span><b>Congratulations!</b> The auction has beend closed and <b>you are the highest bidder!</b></span>
</div>
{% else %}
<div class="alert alert-secondary" role="alert">
    <span>The Auction has been closed. <b>Highest bider: {{ highestBidder|title }}</b></span>
</div>
{% endif %}
{% endif %}
<form style="text-align:left;" action="" method="post">
    {% csrf_token %}
    {% if watchlist == 1 %}
    <input id="removeFromWatchlist" class="btn btn-primary" type="submit" value="Remove from Watchlist">
    <input name="action" value="watchlist_remove" type="hidden">
    <input name="watchlistItem" value="{{ listing|get_item:"title" }}" type="hidden">
    {% else %}
    <input id="addToWatchlist" class="btn btn-primary" type="submit" value="Watchlist">
    <input name="action" value="watchlist_add" type="hidden">
    <input name="watchlistItem" value="{{ listing|get_item:"title" }}" type="hidden">
    {% endif %}
</form>
{% endif %}
<div class="wrapper">
    <div id="listing_img">
        <img src="{{ listing|get_item:"imageURL" }}">
    </div>
    <div>
        <h5 style="font-weight:600">${{ listing|get_item:"bid" }}</h5>
        {% if listing|get_item:"status" == "closed" %}
        <span><b>This auction has been closed.</b></span>
        {% endif %}
    </div>
    {% if user.is_authenticated and listing|get_item:"status" == "opened" %}
    {% if request.user != listing|get_item:"createdBy" %}
    <form action="{% url 'commerce:listing' listing|get_item:"title"%}" method="post">
        <div class="form-group">
            {% csrf_token %}
            {{ placeBid.bid }}
            <input id="submit" class="btn btn-primary" type="submit" value="Place Bid">
            <input name="action" value="bid" type="hidden">
            <input name="placedTo" value="{{ listing|get_item:"title" }}" type="hidden">
            <input name="currentBid" value="{{ listing|get_item:"bid" }}" type="hidden">
            <input name="placedBy" value="{{ user.id }}" type="hidden">
        </div>
    </form>
    {% else %}
    <form action="" method="post">
        {% csrf_token %}
        <input name="action" value="close_auction" type="hidden">
        <input name="listingTitle" value="{{ listing|get_item:"title" }}" type="hidden">
        <input id="close_Auction" class="btn btn-primary" type="submit" value="Close Auction">
    </form>
    {% endif %}
    {% endif %}
    <div style="margin-top:30px;">
        <h4>Details</h4>
        <ul>
            <li>Listed by {{ listing|get_item:"createdBy" |title }}</li>
            <li>Category: {{ listing|get_item:"category" }}</li>
        </ul>
    </div>
    <div>
        <h4>Comments</h4>
        {% if user.is_authenticated and request.user != listing|get_item:"createdBy" %}
        <p>
            <a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample1" role="button"
                aria-expanded="false" aria-controls="multiCollapseExample1">Write a comment</a>
        </p>
        <div class="row">
            <div class="col">
                <div class="collapse multi-collapse" id="multiCollapseExample1">
                    <div class="card card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            {{ commentForm }}
                            <input name="action" value="comment" type="hidden">
                            <input name="commentBy" value="{{ request.user }}" type="hidden">
                            <input style="margin-top:10px;" class="btn btn-primary" type="submit" value="Send">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <div>
            {% for cmmt in comments %}
            <span>
                {{ cmmt.commentBy|title}}
            </span>
            <br>
            <b>
                {{ cmmt.title }}
            </b>
            <br>
            <span>
                {{ cmmt.comment }}
            </span>
            <br>
            <br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

<h2>Login</h2>

{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'commerce:login' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input autofocus class="form-control" type="text" name="username" placeholder="Username">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="password" placeholder="Password">
    </div>
    <input class="btn btn-primary" type="submit" value="Login">
</form>

Don't have an account? <a href="{% url 'commerce:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

<h2>Register</h2>

{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'commerce:register' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input class="form-control" autofocus type="text" name="username" placeholder="Username">
    </div>
    <div class="form-group">
        <input class="form-control" type="email" name="email" placeholder="Email Address">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="password" placeholder="Password">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
    </div>
    <input class="btn btn-primary" type="submit" value="Register">
</form>

Already have an account? <a href="{% url 'commerce:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Your Watchlist</h2>
{% if watchlistLen > 0 %}
{% for listing in watchlist %}
<div id="listing">
    <div id="imgOuter">
        <div style="width:100%;">
            <img src="{{ listing.imageURL }}">
        </div>
    </div>
    <div id="descriptionOuter">
        <div>
            <h4><a href="{% url 'commerce:listing' listing.title %}">{{ listing.title }}</a></h4>
        </div>
        <div><b>Price:</b> ${{ listing.bid }}</div>
        <div>{{ listing.description }}</div>
    </div>
</div>
{% endfor %}
{% else %}
<h5>Nothing on your watchlist yet...</h5>
{% endif %}
{% endblock %}